export const ProductsData = [
  {
    id: 1,
    title: "sphynx Tie Dye Grey T-shirt",
    sku: 186441193304491312,
    quantity: 1,
    description: "sphynx Tie Dye Grey",
    availableSize: ["X", "L", "XL", "XXL"],
    price: 10,
    isFreeShipping: true,
  },
  {
    id: 2,
    title: "Danger Knife Grey T-shirt",
    sku: 11854078013954528,
    quantity: 1,
    description: "Danger Knife Grey",
    availableSize: ["x", "M", "L"],
    price: 14.9,
    isFreeShipping: true,
  },
  {
    id: 3,
    title: "White DGK Script Tee",
    sku: 876661122392077,
    quantity: 1,
    description: "White DGK Script",
    availableSize: ["X", "M", "L"],
    price: 14.9,
    isFreeShipping: true,
  },
  {
    id: 4,
    title: "Born On The Streets T-Shirt",
    sku: 9197907543445677,
    quantity: 1,
    description: "Born On The Streets",
    availableSize: ["XL"],
    price: 25.9,
    isFreeShipping: false,
  },
  {
    id: 5,
    title: "Tso 3D Short Sleeve",
    sku: 10547961582846888,
    quantity: 1,
    description: "Tso 3D Short Sleeve",
    availableSize: ["X", "XL", "L"],
    price: 10.9,
    isFreeShipping: false,
  },
  {
    id: 6,
    title: "Man Tie Cinze Dye Grey T-Shirt",
    sku: 609048479343891,
    quantity: 1,
    description: "Man Tie Cinze Dye Grey",
    availableSize: ["XXL", "XL"],
    price: 49.9,
    isFreeShipping: false,
  },
  {
    id: 7,
    title: "Crazy Monkey Black T-Shirt",
    sku: 18532669286405324,
    quantity: 1,
    description: "1977 Infantil",
    availableSize: ["S"],
    style: "Preto com listras brancas",
    price: 22.5,
    isFreeShipping: true,
  },
  {
    id: 8,
    title: "Tso 3D Black T-Shirt",
    sku: 5619496040738316,
    quantity: 1,
    description: "",
    availableSize: ["XL"],
    style: "Azul escuro",
    price: 18.7,
    isFreeShipping: false,
  },
  {
    id: 9,
    title: "Crazy Monkey Black T-Shirt",
    sku: 11600983276356165,
    quantity: 1,
    description: "",
    availableSize: ["L", "XL"],
    price: 134.9,
    isFreeShipping: true,
  },
];
